### ISSUE TITLE
Implementing mkdir, cd, or ls?

### ISSUE THREAD

**Issue by sirjohnsonson** [m4tt72/terminal#19]
Hi, thanks for making this great project! Do you have any plans to implement more functions, such as mkdir/cd/ls? I want to upload personal files to my website and it would be great if there are options for that. 

For an example, here is a project I found that implements this pretty well: https://github.com/Jaredk3nt/HomeTerm

**Comment by geekedtv** [comment]
> Hi, thanks for making this great project! Do you have any plans to implement more functions, such as mkdir/cd/ls? I want to upload personal files to my website and it would be great if there are options for that.
> 
> For an example, here is a project I found that implements this pretty well: https://github.com/Jaredk3nt/HomeTerm

This is meant to be a fun website, not an actual working terminal that anyone could hack away on :p

**Comment by m4tt72** [comment]
Hello @sirjohnsonson, thank you for the suggestion.

It's way out of this project's scope to implement shell-like commands, it's meant to have its own "system", where commands can easily be implemented, since they are just functions that return a string, of course I can add mkdir/cd/ls but there is no actual filesystem that they will operate on.

Think of is as a really dumb, stripped down version of a shell, It's purely frontend.
